project:
  type: website
  output_dir: docs

website:
  title: "Calvin's Data Science Journey"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/calvpang
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
